from enum import Enum, auto
from typing import NamedTuple, Optional

from BaseClasses import Location, Region

CITY_TRIAL_BASE_CHECKLIST_ADDRESS = 0x805369FC


class KARLocationType(Enum):
    """
    This class defines constants for various types of locations in Kirby Air Ride.
    """

    CHECKLISTBOX = auto()


class KARLocationData(NamedTuple):
    """
    This class represents the data for a location in Kirby Air Ride.

    :param code: The unique code identifier for the location.
    :param region: The name of the region where the location resides.
    :param reward: The reward for the location.
    :param type: The type of the location.
    :param mem_address: In-memory address of the check.
    """

    code: int
    region: str
    reward: str
    type: KARLocationType
    mem_address: Optional[int] = None


class KARLocation(Location):
    """
    This class represents a location in Kirby Air Ride.

    :param player: The ID of the player whose world the location is in.
    :param name: The name of the location.
    :param parent: The location's parent region.
    :param data: The data associated with this location.
    """

    game: str = "Kirby Air Ride"

    def __init__(self, player: int, name: str, parent: Region, data: KARLocationData):
        address = None if data.code is None else data.code
        super().__init__(player, name, address=address, parent=parent)

        self.data = data


CITY_TRIAL_LOCATION_TABLE: dict[str, KARLocationData] = {
    "City Trial: race over 60 miles!": KARLocationData(
        1,
        "City Trial",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS,
    ),
    "City Trial: pick up a total of over 1000 items!": KARLocationData(
        2,
        "City Trial",
        "Music: City (All: X or Y button + Start/Pause)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 4,
    ),
    "City Trial: break more than 1000 boxes!": KARLocationData(
        3,
        "City Trial",
        "Meta Knight: Select in free run mode",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 8,
    ),
    "Stadium: play in over 10 stadium modes!": KARLocationData(
        4,
        "City Trial",
        "New Stadium: Single Race (Nebula Belt)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 12,
    ),
    "Stadium: DRAG RACE 2 Finish in less than 00:24:00!": KARLocationData(
        5,
        "Stadium: DRAG RACE 2",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 16,
    ),
    "Stadium: DRAG RACE 4 Finish in less than 00:24:00!": KARLocationData(
        6,
        "Stadium: DRAG RACE 4",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 20,
    ),
    "Stadium: HIGH JUMP Stay airborne longer than 10 seconds!": KARLocationData(
        7,
        "Stadium: HIGH JUMP",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 24,
    ),
    "Stadium: TARGET FLIGHT stay airborne longer than 15 seconds!": KARLocationData(
        8,
        "Stadium: TARGET FLIGHT",
        "Sound Test: Target Flight",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 28,
    ),
    "Stadium: AIR GLIDER fly more than 660 feet!": KARLocationData(
        9,
        "Stadium: AIR GLIDER",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 32,
    ),
    "Stadium: DESTRUCTION DERBY 2 In one game, KO your rivals 5 or more times!": KARLocationData(
        10,
        "Stadium: DESTRUCTION DERBY 2",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 36,
    ),
    "Stadium: DESTRUCTION DERBY 1 bust all the rocks on the field!": KARLocationData(
        11,
        "Stadium: DESTRUCTION DERBY 1",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 40,
    ),
    "Stadium: KIRBY MELEE 2 In one game, KO enemies over 30 times!": KARLocationData(
        12,
        "Stadium: KIRBY MELEE 2",
        "Sound Test: What's in the box?",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 44,
    ),
    "City Trial: Do some damage to Dyna Blade!": KARLocationData(
        13,
        "City Trial",
        "Sound Test: Dyna Blade Intro",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 48,
    ),
    "City Trial: Steal over 8 items from Tac by yourself!": KARLocationData(
        14,
        "City Trial",
        "Sound Test: Tac Challenge",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 52,
    ),
    "City Trial: Go into the castle chamber when it opens!": KARLocationData(
        15,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 56,
    ),
    "City Trial: Open up all the holes around the base of the volcano!": KARLocationData(
        16,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 60,
    ),
    "City Trial: During one game, go into the hole in the high plains 3 times or more!": KARLocationData(
        17,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 64,
    ),
    "City Trial: Destroy all of the dilapidated houses!": KARLocationData(
        18,
        "City Trial",
        "Hydra Part X: Use 3 to complete Hydra",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 68,
    ),
    "City Trial: Get 10 items within the first 20 seconds of the match!": KARLocationData(
        19,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 72,
    ),
    "City Trial: Let time run out while all players are on the rails!": KARLocationData(
        20,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 76,
    ),
    "City Trial: In one game, get over 10 Boost Patches!": KARLocationData(
        21,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 80,
    ),
    "City Trial: In one game, get 10 or more Turn Patches!": KARLocationData(
        22,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 84,
    ),
    "City Trial: In one game, get 10 or more Weight Patches!": KARLocationData(
        23,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 88,
    ),
    "City Trial: In one game, get 10 or more Glide Patches!": KARLocationData(
        24,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 92,
    ),
    "City Trial: Use Fireworks to KO rivals 10 times or more!": KARLocationData(
        25,
        "City Trial",
        "Green Kirby:(X or Y button on player entry)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 96,
    ),
    "Stadium: DRAG RACE 1 Finish in less than 00:17:00 on Formula Star!": KARLocationData(
        26,
        "Stadium: DRAG RACE 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 100,
    ),
    "Stadium: DRAG RACE 3 Finish in less than 00:31:00 on Wheelie Bike!": KARLocationData(
        27,
        "Stadium: DRAG RACE 3",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 104,
    ),
    "City Trial: In one race, eat 3 or more Hot Dogs!": KARLocationData(
        28,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 108,
    ),
    "City Trial: In the city, bust Wheelie Bike while riding on Warpstar!": KARLocationData(
        29,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 112,
    ),
    "City Trial: In the city, bust Slick Star while riding on Formula Star!": KARLocationData(
        30,
        "City Trial",
        "Sound Test: Station Fire",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 116,
    ),
    "City Trial: Race over 200 miles!": KARLocationData(
        31,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 1,
    ),
    "City Trial: Pick up a total of over 3000 items!": KARLocationData(
        32,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 4 + 1,
    ),
    "Free Run: Drive for a total of 10 minutes or more!": KARLocationData(
        33,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 8 + 1,
    ),
    "Stadium: play in over 20 stadium modes!": KARLocationData(
        34,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 12 + 1,
    ),
    "Stadium: DRAG RACE 2 Finish in less than 00:20:00!": KARLocationData(
        35,
        "Stadium: DRAG RACE 2",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 16 + 1,
    ),
    "Stadium: DRAG RACE 4 Finish in less than 00:19:00!": KARLocationData(
        36,
        "Stadium: DRAG RACE 4",
        "Sound Test: Drag Race",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 20 + 1,
    ),
    "Stadium: TARGET FLIGHT In one game, get over 150 points!": KARLocationData(
        37,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 24 + 1,
    ),
    "Stadium: TARGET FLIGHT play 15 times or more!": KARLocationData(
        38,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 28 + 1,
    ),
    "Stadium: AIR GLIDER fly more than 1,300 feet!": KARLocationData(
        39,
        "Stadium: AIR GLIDER",
        "Dragoon Part C: Use 3 to complete Dragoon",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 32 + 1,
    ),
    "Stadium: DESTRUCTION DERBY 3 In one game, KO your rivals 5 or more times!": KARLocationData(
        40,
        "Stadium: DESTRUCTION DERBY 3",
        "New Stadium: Destruction Derby 4",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 36 + 1,
    ),
    "Stadium: DESTRUCTION DERBY (All) KO enemies over 50 times!": KARLocationData(
        41,
        "Stadium: DESTRUCTION DERBY ALL",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 40 + 1,
    ),
    "Stadium: KIRBY MELEE (All) KO over 500 enemies!": KARLocationData(
        42,
        "Stadium: KIRBY MELEE ALL",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 44 + 1,
    ),
    "City Trial: Get trampled by Dyna Blade!": KARLocationData(
        43,
        "City Trial",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 48 + 1,
    ),
    "City Trial: The meteor attacks the city 3 or more times!": KARLocationData(
        44,
        "City Trial",
        "Sound Test: Flying Meteor",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 52 + 1,
    ),
    "City Trial: During one game, fly through the rings in the sky 5 times or more!": KARLocationData(
        45,
        "City Trial",
        "Dragoon Part B: Use 3 to complete Dragoon",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 56 + 1,
    ),
    "City Trial: Let the waterwheel carry you 10 times or more!": KARLocationData(
        46,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 60 + 1,
    ),
    "City Trial: During one game, break all of the volcano rocks and high plains rocks!": KARLocationData(
        47,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 64 + 1,
    ),
    "City Trial: Knock down all of the trees in the forest!": KARLocationData(
        48,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 68 + 1,
    ),
    "City Trial: Do damage to a rival within the first 10 seconds of a match!": KARLocationData(
        49,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 72 + 1,
    ),
    "City Trial: Break a CPU's machine 5 times or more in the city!": KARLocationData(
        50,
        "City Trial",
        "Purple Kirby: (X or Y button on Player Entry)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 76 + 1,
    ),
    "Stadium: DESTRUCTION DERBY 1 In one game, KO a rival 10 times or more!": KARLocationData(
        51,
        "Stadium: DESTRUCTION DERBY 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 80 + 1,
    ),
    "Stadium: DESTRUCTION DERBY 4 In one game, KO a rival 10 times or more!": KARLocationData(
        52,
        "Stadium: DESTRUCTION DERBY 4",
        "New Stadium: Destruction Derby 5",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 84 + 1,
    ),
    "Stadium: KIRBY MELEE 1 In one game, KO over 75 enemies by yourself!": KARLocationData(
        53,
        "Stadium: KIRBY MELEE 1",
        "New Stadium: Kirby Melee 2",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 88 + 1,
    ),
    "City Trial: Get 30 or more Glide Patches!": KARLocationData(
        54,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 92 + 1,
    ),
    "City Trial: In one game, eat 2 or more maxim tomatoes!": KARLocationData(
        55,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 96 + 1,
    ),
    "Stadium: DRAG RACE 2 Finish in less than 00:27:00 on Wagon Star!": KARLocationData(
        56,
        "Stadium: DRAG RACE 2",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 100 + 1,
    ),
    "Stadium: DRAG RACE 4 Finish in less than 00:33:00 on Turbo Star!": KARLocationData(
        57,
        "Stadium: DRAG RACE 4",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 104 + 1,
    ),
    "Unlock Dragoon Parts A, B, and C on the Checklist!": KARLocationData(
        58,
        "City Trial",
        "Dragoon: Select in Free Run mode",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 108 + 1,
    ),
    "City Trial: In the city, bust Swerve Star while riding on Wheelie Bike!": KARLocationData(
        59,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 112 + 1,
    ),
    "City Trial: In the city, bust Rocket Star while riding on Slick Star!": KARLocationData(
        60,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 116 + 1,
    ),
    "City Trial: Pick up a total of over 100 items!": KARLocationData(
        61,
        "City Trial",
        "Sound Test: Item bounce",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 2,
    ),
    "Free Run: Change Air Ride Machines 10 times or more!": KARLocationData(
        62,
        "City Trial",
        "Sound Test: Legendary Air Ride Machine",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 4 + 2,
    ),
    "Free Run: Drive for a total of 30 minutes or more!": KARLocationData(
        63,
        "City Trial",
        "Sound Test: City Trial",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 8 + 2,
    ),
    "Stadium: DRAG RACE 1 Finish in less than 00:24:00!": KARLocationData(
        64,
        "Stadium: DRAG RACE 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 12 + 2,
    ),
    "Stadium: DRAG RACE 3 Finish in less than 00:35:00!": KARLocationData(
        65,
        "Stadium: DRAG RACE 3",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 16 + 2,
    ),
    "Stadium: HIGH JUMP Jump higher than 500 feet!": KARLocationData(
        66,
        "Stadium: HIGH JUMP",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 20 + 2,
    ),
    "Stadium: TARGET FLIGHT In one game, get exactly 90 points!": KARLocationData(
        67,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 24 + 2,
    ),
    "Stadium: TARGET FLIGHT get more than 1,500 points!": KARLocationData(
        68,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 28 + 2,
    ),
    "Stadium: AIR GLIDER stay airborne longer than 30 seconds!": KARLocationData(
        69,
        "Stadium: AIR GLIDER",
        "Sound Test: Air Glider",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 32 + 2,
    ),
    "Stadium: DESTRUCTION DERBY 4 In one game, KO your rivals 5 or more times!": KARLocationData(
        70,
        "Stadium: DESTRUCTION DERBY 4",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 36 + 2,
    ),
    "Stadium: DESTRUCTION DERBY (All) KO enemies over 150 times!": KARLocationData(
        71,
        "Stadium: DESTRUCTION DERBY ALL",
        "Hydra Part Y: Use 3 to complete Hydra",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 40 + 2,
    ),
    "Stadium: KIRBY MELEE (All) KO over 1,500 enemies!": KARLocationData(
        72,
        "Stadium: KIRBY MELEE ALL",
        "Hydra Part Z: Use 3 to complete Hydra",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 44 + 2,
    ),
    "City Trial: Break 5 or more of the huge pillars that appear!": KARLocationData(
        73,
        "City Trial",
        "Sound Test: Huge Pillar",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 48 + 2,
    ),
    "City Trial: Use up one of the restoration areas!": KARLocationData(
        74,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 52 + 2,
    ),
    "City Trial: Bust the star pole!": KARLocationData(
        75,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 56 + 2,
    ),
    "City Trial: Make your way to the garden in the sky!": KARLocationData(
        76,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 60 + 2,
    ),
    "City Trial: Use the grind rail to break into the crater!": KARLocationData(
        77,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 64 + 2,
    ),
    "City Trial: Get the Bomb ability from the Copy Chance Wheel!": KARLocationData(
        78,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 68 + 2,
    ),
    "City Trial: Have all players simultaneously get off of their machines!": KARLocationData(
        79,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 72 + 2,
    ),
    "City Trial: Enter a race with 3 CPU Players and do damage to all of them in the city!": KARLocationData(
        80,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 76 + 2,
    ),
    "City Trial: In one game, get 10 or more Top Speed Patches!": KARLocationData(
        81,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 80 + 2,
    ),
    "City Trial: In one game, get 10 or more Charge Patches!": KARLocationData(
        82,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 84 + 2,
    ),
    "City Trial: In one game, get 10 or more Defense Patches!": KARLocationData(
        83,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 88 + 2,
    ),
    "City Trial: Use Sensor Bombs to KO rivals 3 times or more!": KARLocationData(
        84,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 92 + 2,
    ),
    "City Trial: In one game, drink 3 or more energy drinks!": KARLocationData(
        85,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 96 + 2,
    ),
    "Stadium: DRAG RACE 2 Finish in less than 00:29:00 on Winged Star!": KARLocationData(
        86,
        "Stadium: DRAG RACE 2",
        "Brown Kirby:(X or Y button on player entry)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 100 + 2,
    ),
    "Stadium: DRAG RACE 4 Finish in less than 00:24:00 on Rex Wheelie!": KARLocationData(
        87,
        "Stadium: DRAG RACE 4",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 104 + 2,
    ),
    "Unlock Hydra Parts X, Y, and Z on the Checklist!": KARLocationData(
        88,
        "City Trial",
        "Hydra: Select in Free Run mode",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 108 + 2,
    ),
    "City Trial: In the city, bust Warpstar while riding on Swerve Star!": KARLocationData(
        89,
        "City Trial",
        "Sound Test: The Lighthouse Light Burns",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 112 + 2,
    ),
    "City Trial: In the city, bust Turbo Star while riding on Rocket Star!": KARLocationData(
        90,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 116 + 2,
    ),
    "City Trial: pick up a total of over 500 items!": KARLocationData(
        91,
        "City Trial",
        "Bonus: Pause screen power-ups",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 3,
    ),
    "City Trial: break more than 500 boxes!": KARLocationData(
        92,
        "City Trial",
        "Sound test: dense fog today",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 4 + 3,
    ),
    "Free Run: Drive for a total of 2 hours or more!": KARLocationData(
        93,
        "City Trial",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 8 + 3,
    ),
    "Stadium: DRAG RACE 1 Finish in less than 00:20:00!": KARLocationData(
        94,
        "Stadium: DRAG RACE 1",
        "Sound Test: rowdy charge tank",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 12 + 3,
    ),
    "Stadium: DRAG RACE 3 Finish in less than 00:27:00!": KARLocationData(
        95,
        "Stadium: DRAG RACE 3",
        "New Stadium: Drag Race 4",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 16 + 3,
    ),
    "Stadium: HIGH JUMP Jump higher than 1,000 feet!": KARLocationData(
        96,
        "Stadium: HIGH JUMP",
        "Dragoon Part A: Use 3 to complete Dragoon",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 20 + 3,
    ),
    "Stadium: TARGET FLIGHT In one game, get a perfect score: 200 points!": KARLocationData(
        97,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 24 + 3,
    ),
    "Stadium: AIR GLIDER fly more than 330 feet!": KARLocationData(
        98,
        "Stadium: AIR GLIDER",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 28 + 3,
    ),
    "Stadium: DESTRUCTION DERBY 1 In one game, KO your rivals 5 or more times!": KARLocationData(
        99,
        "Stadium: DESTRUCTION DERBY 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 32 + 3,
    ),
    "Stadium: DESTRUCTION DERBY 5 In one game, KO your rivals 5 or more times!": KARLocationData(
        100,
        "Stadium: DESTRUCTION DERBY 5",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 36 + 3,
    ),
    "Stadium: KIRBY MELEE 1 In one game, KO enemies over 50 times!": KARLocationData(
        101,
        "Stadium: KIRBY MELEE 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 40 + 3,
    ),
    "Stadium: VS. KING DEDEDE KO King Dedede in less than a minute!": KARLocationData(
        102,
        "Stadium: VS. KING DEDEDE",
        "King Dedede: Select in free run mode",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 44 + 3,
    ),
    "City Trial: Break a huge pillar within 40 seconds of the time it appears!": KARLocationData(
        103,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 48 + 3,
    ),
    "Fill in over 100 Checklist blocks!": KARLocationData(
        104,
        "City Trial",
        "Ending: view with the A button",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 52 + 3,
    ),
    "City Trial: Bust the star pole 10 times or more!": KARLocationData(
        105,
        "City Trial",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 56 + 3,
    ),
    "City Trial: Open up the pitfall in the forest!": KARLocationData(
        106,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 60 + 3,
    ),
    "City Trial: Jump on top of the building 10 times or more using the super jump ramp!": KARLocationData(
        107,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 64 + 3,
    ),
    "City Trial: Get the Sleep ability from the Copy Chance Wheel!": KARLocationData(
        108,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 68 + 3,
    ),
    "City Trial: Let time run out while all players are off of their machines!": KARLocationData(
        109,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 72 + 3,
    ),
    "City Trial: In one game, get 50 or more items!": KARLocationData(
        110,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 76 + 3,
    ),
    "Stadium: DESTRUCTION DERBY 2 In one game, KO a rival 10 times or more!": KARLocationData(
        111,
        "Stadium: DESTRUCTION DERBY 2",
        "New Stadium: Destruction Derby 3",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 80 + 3,
    ),
    "Stadium: DESTRUCTION DERBY 5 In one game, KO a rival 10 times or more!": KARLocationData(
        112,
        "Stadium: DESTRUCTION DERBY 5",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 84 + 3,
    ),
    "Stadium: KIRBY MELEE 2 In one game, KO over 40 enemies by yourself!": KARLocationData(
        113,
        "Stadium: KIRBY MELEE 2",
        "Sound Test: Kirby Melee",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 88 + 3,
    ),
    "City Trial: Use Gold Spikes to KO rivals 3 times or more!": KARLocationData(
        114,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 92 + 3,
    ),
    "Stadium: DRAG RACE 1 Finish in less than 00:26:00 on Warpstar!": KARLocationData(
        115,
        "Stadium: DRAG RACE 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 96 + 3,
    ),
    "Stadium: DRAG RACE 3 Finish in less than 00:28:00 on Swerve Star!": KARLocationData(
        116,
        "Stadium: DRAG RACE 3",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 100 + 3,
    ),
    "City Trial: In one race, eat 3 or more plates of sushi!": KARLocationData(
        117,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 104 + 3,
    ),
    "City Trial: In the city, bust Wheelie Scooter while riding Compact Star!": KARLocationData(
        118,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 108 + 3,
    ),
    "City Trial: In the city, bust Formula Star while riding on Turbo Star!": KARLocationData(
        119,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 112 + 3,
    ),
    "In one match, complete both Dragoon and Hydra!": KARLocationData(
        120,
        "City Trial",
        "White Kirby:(X or Y button on player entry)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 116 + 3,
    ),
}

LOCATION_LOOKUP_ID_TO_NAME: dict[int, str] = {
    location_data.code: location_name
    for location_name, location_data in CITY_TRIAL_LOCATION_TABLE.items()
    if location_data.code is not None
}

location_name_groups = {
    "Stadiums": {
        "Stadium: play in over 10 stadium modes!",
        "Stadium: DRAG RACE 2 Finish in less than 00:24:00!",
        "Stadium: DRAG RACE 4 Finish in less than 00:24:00!",
        "Stadium: HIGH JUMP Stay airborne longer than 10 seconds!",
        "Stadium: TARGET FLIGHT stay airborne longer than 15 seconds!",
        "Stadium: AIR GLIDER fly more than 660 feet!",
        "Stadium: DESTRUCTION DERBY 2 In one game, KO your rivals 5 or more times!",
        "Stadium: DESTRUCTION DERBY 1 bust all the rocks on the field!",
        "Stadium: KIRBY MELEE 2 In one game, KO enemies over 30 times!",
        "Stadium: DRAG RACE 1 Finish in less than 00:17:00 on Formula Star!",
        "Stadium: DRAG RACE 3 Finish in less than 00:31:00 on Wheelie Bike!",
        "Stadium: play in over 20 stadium modes!",
        "Stadium: DRAG RACE 2 Finish in less than 00:20:00!",
        "Stadium: DRAG RACE 4 Finish in less than 00:19:00!",
        "Stadium: TARGET FLIGHT In one game, get over 150 points!",
        "Stadium: TARGET FLIGHT play 15 times or more!",
        "Stadium: AIR GLIDER fly more than 1,300 feet!",
        "Stadium: DESTRUCTION DERBY 3 In one game, KO your rivals 5 or more times!",
        "Stadium: DESTRUCTION DERBY (All) KO enemies over 50 times!",
        "Stadium: KIRBY MELEE (All) KO over 500 enemies!",
        "Stadium: DESTRUCTION DERBY 1 In one game, KO a rival 10 times or more!",
        "Stadium: DESTRUCTION DERBY 4 In one game, KO a rival 10 times or more!",
        "Stadium: KIRBY MELEE 1 In one game, KO over 75 enemies by yourself!",
        "Stadium: DRAG RACE 2 Finish in less than 00:27:00 on Wagon Star!",
        "Stadium: DRAG RACE 4 Finish in less than 00:33:00 on Turbo Star!",
        "Stadium: DRAG RACE 1 Finish in less than 00:24:00!",
        "Stadium: DRAG RACE 3 Finish in less than 00:35:00!",
        "Stadium: HIGH JUMP Jump higher than 500 feet!",
        "Stadium: TARGET FLIGHT In one game, get exactly 90 points!",
        "Stadium: TARGET FLIGHT get more than 1,500 points!",
        "Stadium: AIR GLIDER stay airborne longer than 30 seconds!",
        "Stadium: DESTRUCTION DERBY 4 In one game, KO your rivals 5 or more times!",
        "Stadium: DESTRUCTION DERBY (All) KO enemies over 150 times!",
        "Stadium: KIRBY MELEE (All) KO over 1,500 enemies!",
        "Stadium: DRAG RACE 2 Finish in less than 00:29:00 on Winged Star!",
        "Stadium: DRAG RACE 4 Finish in less than 00:24:00 on Rex Wheelie!",
        "Stadium: DRAG RACE 1 Finish in less than 00:20:00!",
        "Stadium: DRAG RACE 3 Finish in less than 00:27:00!",
        "Stadium: HIGH JUMP Jump higher than 1,000 feet!",
        "Stadium: TARGET FLIGHT In one game, get a perfect score: 200 points!",
        "Stadium: AIR GLIDER fly more than 330 feet!",
        "Stadium: DESTRUCTION DERBY 1 In one game, KO your rivals 5 or more times!",
        "Stadium: DESTRUCTION DERBY 5 In one game, KO your rivals 5 or more times!",
        "Stadium: KIRBY MELEE 1 In one game, KO enemies over 50 times!",
        "Stadium: VS. KING DEDEDE KO King Dedede in less than a minute!",
        "Stadium: DESTRUCTION DERBY 2 In one game, KO a rival 10 times or more!",
        "Stadium: DESTRUCTION DERBY 5 In one game, KO a rival 10 times or more!",
        "Stadium: KIRBY MELEE 2 In one game, KO over 40 enemies by yourself!",
        "Stadium: DRAG RACE 1 Finish in less than 00:26:00 on Warpstar!",
        "Stadium: DRAG RACE 3 Finish in less than 00:28:00 on Swerve Star!",
    },
    "Multiplayer": {
        "City Trial: Let time run out while all players are on the rails!",
        "City Trial: Have all players simultaneously get off of their machines!",
        "City Trial: Let time run out while all players are off of their machines!",
    },
    "CPUs": {
        "City Trial: Break a CPU's machine 5 times or more in the city!",
        "City Trial: Enter a race with 3 CPU Players and do damage to all of them in the city!",
        "City Trial: Do damage to a rival within the first 10 seconds of a match!",
    },
    "Bust Vehicle on Vehicle": {
        "City Trial: In the city, bust Wheelie Bike while riding on Warpstar!",
        "City Trial: In the city, bust Slick Star while riding on Formula Star!",
        "City Trial: In the city, bust Swerve Star while riding on Wheelie Bike!",
        "City Trial: In the city, bust Rocket Star while riding on Slick Star!",
        "City Trial: In the city, bust Warpstar while riding on Swerve Star!",
        "City Trial: In the city, bust Turbo Star while riding on Rocket Star!",
        "City Trial: In the city, bust Wheelie Scooter while riding Compact Star!",
        "City Trial: In the city, bust Formula Star while riding on Turbo Star!",
    },
    "Events": {
        "City Trial: Use up one of the restoration areas!",
        "City Trial: The meteor attacks the city 3 or more times!",
        "City Trial: Do some damage to Dyna Blade!",
        "City Trial: Get trampled by Dyna Blade!",
        "City Trial: Steal over 8 items from Tac by yourself!",
    },
    "Patches": {
        "City Trial: In one game, get over 10 Boost Patches!",
        "City Trial: In one game, get 10 or more Turn Patches!",
        "City Trial: In one game, get 10 or more Weight Patches!",
        "City Trial: In one game, get 10 or more Glide Patches!",
        "City Trial: Get 30 or more Glide Patches!",
        "City Trial: In one game, get 10 or more Top Speed Patches!",
        "City Trial: In one game, get 10 or more Charge Patches!",
        "City Trial: In one game, get 10 or more Defense Patches!",
    },
}
