from enum import Enum, auto
from typing import NamedTuple, Optional

from BaseClasses import Location, Region

CITY_TRIAL_BASE_CHECKLIST_ADDRESS = 0x805369FC
AIR_RIDE_BASE_CHECKLIST_ADDRESS = 0x805367BC


class KARLocationType(Enum):
    """
    This class defines constants for various types of locations in Kirby Air Ride.
    """

    CHECKLISTBOX = auto()


class KARLocationData(NamedTuple):
    """
    This class represents the data for a location in Kirby Air Ride.

    :param code: The unique code identifier for the location.
    :param region: The name of the region where the location resides.
    :param reward: The reward for the location.
    :param type: The type of the location.
    :param mem_address: In-memory address of the check.
    """

    code: int
    region: str
    reward: str
    type: KARLocationType
    mem_address: Optional[int] = None


class KARLocation(Location):
    """
    This class represents a location in Kirby Air Ride.

    :param player: The ID of the player whose world the location is in.
    :param name: The name of the location.
    :param parent: The location's parent region.
    :param data: The data associated with this location.
    """

    game: str = "Kirby Air Ride"

    def __init__(self, player: int, name: str, parent: Region, data: KARLocationData):
        address = None if data.code is None else data.code
        super().__init__(player, name, address=address, parent=parent)

        self.data = data


CITY_TRIAL_LOCATION_TABLE: dict[str, KARLocationData] = {
    "City Trial: race over 60 miles!": KARLocationData(
        1,
        "City Trial",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS,
    ),
    "City Trial: pick up a total of over 1000 items!": KARLocationData(
        2,
        "City Trial",
        "Music: City (All: X or Y button + Start/Pause)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 4,
    ),
    "City Trial: break more than 1000 boxes!": KARLocationData(
        3,
        "City Trial",
        "Meta Knight: Select in free run mode",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 8,
    ),
    "Stadium: play in over 10 stadium modes!": KARLocationData(
        4,
        "City Trial",
        "New Stadium: Single Race (Nebula Belt)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 12,
    ),
    "Stadium: DRAG RACE 2 Finish in less than 00:24:00!": KARLocationData(
        5,
        "Stadium: DRAG RACE 2",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 16,
    ),
    "Stadium: DRAG RACE 4 Finish in less than 00:24:00!": KARLocationData(
        6,
        "Stadium: DRAG RACE 4",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 20,
    ),
    "Stadium: HIGH JUMP Stay airborne longer than 10 seconds!": KARLocationData(
        7,
        "Stadium: HIGH JUMP",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 24,
    ),
    "Stadium: TARGET FLIGHT stay airborne longer than 15 seconds!": KARLocationData(
        8,
        "Stadium: TARGET FLIGHT",
        "Sound Test: Target Flight",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 28,
    ),
    "Stadium: AIR GLIDER fly more than 660 feet!": KARLocationData(
        9,
        "Stadium: AIR GLIDER",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 32,
    ),
    "Stadium: DESTRUCTION DERBY 2 In one game, KO your rivals 5 or more times!": KARLocationData(
        10,
        "Stadium: DESTRUCTION DERBY 2",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 36,
    ),
    "Stadium: DESTRUCTION DERBY 1 bust all the rocks on the field!": KARLocationData(
        11,
        "Stadium: DESTRUCTION DERBY 1",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 40,
    ),
    "Stadium: KIRBY MELEE 2 In one game, KO enemies over 30 times!": KARLocationData(
        12,
        "Stadium: KIRBY MELEE 2",
        "Sound Test: What's in the box?",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 44,
    ),
    "City Trial: Do some damage to Dyna Blade!": KARLocationData(
        13,
        "City Trial",
        "Sound Test: Dyna Blade Intro",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 48,
    ),
    "City Trial: Steal over 8 items from Tac by yourself!": KARLocationData(
        14,
        "City Trial",
        "Sound Test: Tac Challenge",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 52,
    ),
    "City Trial: Go into the castle chamber when it opens!": KARLocationData(
        15,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 56,
    ),
    "City Trial: Open up all the holes around the base of the volcano!": KARLocationData(
        16,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 60,
    ),
    "City Trial: During one game, go into the hole in the high plains 3 times or more!": KARLocationData(
        17,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 64,
    ),
    "City Trial: Destroy all of the dilapidated houses!": KARLocationData(
        18,
        "City Trial",
        "Hydra Part X: Use 3 to complete Hydra",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 68,
    ),
    "City Trial: Get 10 items within the first 20 seconds of the match!": KARLocationData(
        19,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 72,
    ),
    "City Trial: Let time run out while all players are on the rails!": KARLocationData(
        20,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 76,
    ),
    "City Trial: In one game, get over 10 Boost Patches!": KARLocationData(
        21,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 80,
    ),
    "City Trial: In one game, get 10 or more Turn Patches!": KARLocationData(
        22,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 84,
    ),
    "City Trial: In one game, get 10 or more Weight Patches!": KARLocationData(
        23,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 88,
    ),
    "City Trial: In one game, get 10 or more Glide Patches!": KARLocationData(
        24,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 92,
    ),
    "City Trial: Use Fireworks to KO rivals 10 times or more!": KARLocationData(
        25,
        "City Trial",
        "Green Kirby:(X or Y button on player entry)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 96,
    ),
    "Stadium: DRAG RACE 1 Finish in less than 00:17:00 on Formula Star!": KARLocationData(
        26,
        "Stadium: DRAG RACE 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 100,
    ),
    "Stadium: DRAG RACE 3 Finish in less than 00:31:00 on Wheelie Bike!": KARLocationData(
        27,
        "Stadium: DRAG RACE 3",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 104,
    ),
    "City Trial: In one race, eat 3 or more Hot Dogs!": KARLocationData(
        28,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 108,
    ),
    "City Trial: In the city, bust Wheelie Bike while riding on Warpstar!": KARLocationData(
        29,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 112,
    ),
    "City Trial: In the city, bust Slick Star while riding on Formula Star!": KARLocationData(
        30,
        "City Trial",
        "Sound Test: Station Fire",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 116,
    ),
    "City Trial: Race over 200 miles!": KARLocationData(
        31,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 1,
    ),
    "City Trial: Pick up a total of over 3000 items!": KARLocationData(
        32,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 4 + 1,
    ),
    "City Trial: Free Run: Drive for a total of 10 minutes or more!": KARLocationData(
        33,
        "City Trial: Free Run",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 8 + 1,
    ),
    "Stadium: play in over 20 stadium modes!": KARLocationData(
        34,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 12 + 1,
    ),
    "Stadium: DRAG RACE 2 Finish in less than 00:20:00!": KARLocationData(
        35,
        "Stadium: DRAG RACE 2",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 16 + 1,
    ),
    "Stadium: DRAG RACE 4 Finish in less than 00:19:00!": KARLocationData(
        36,
        "Stadium: DRAG RACE 4",
        "Sound Test: Drag Race",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 20 + 1,
    ),
    "Stadium: TARGET FLIGHT In one game, get over 150 points!": KARLocationData(
        37,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 24 + 1,
    ),
    "Stadium: TARGET FLIGHT play 15 times or more!": KARLocationData(
        38,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 28 + 1,
    ),
    "Stadium: AIR GLIDER fly more than 1,300 feet!": KARLocationData(
        39,
        "Stadium: AIR GLIDER",
        "Dragoon Part C: Use 3 to complete Dragoon",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 32 + 1,
    ),
    "Stadium: DESTRUCTION DERBY 3 In one game, KO your rivals 5 or more times!": KARLocationData(
        40,
        "Stadium: DESTRUCTION DERBY 3",
        "New Stadium: Destruction Derby 4",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 36 + 1,
    ),
    "Stadium: DESTRUCTION DERBY (All) KO enemies over 50 times!": KARLocationData(
        41,
        "Stadium: DESTRUCTION DERBY ALL",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 40 + 1,
    ),
    "Stadium: KIRBY MELEE (All) KO over 500 enemies!": KARLocationData(
        42,
        "Stadium: KIRBY MELEE ALL",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 44 + 1,
    ),
    "City Trial: Get trampled by Dyna Blade!": KARLocationData(
        43,
        "City Trial",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 48 + 1,
    ),
    "City Trial: The meteor attacks the city 3 or more times!": KARLocationData(
        44,
        "City Trial",
        "Sound Test: Flying Meteor",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 52 + 1,
    ),
    "City Trial: During one game, fly through the rings in the sky 5 times or more!": KARLocationData(
        45,
        "City Trial",
        "Dragoon Part B: Use 3 to complete Dragoon",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 56 + 1,
    ),
    "City Trial: Let the waterwheel carry you 10 times or more!": KARLocationData(
        46,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 60 + 1,
    ),
    "City Trial: During one game, break all of the volcano rocks and high plains rocks!": KARLocationData(
        47,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 64 + 1,
    ),
    "City Trial: Knock down all of the trees in the forest!": KARLocationData(
        48,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 68 + 1,
    ),
    "City Trial: Do damage to a rival within the first 10 seconds of a match!": KARLocationData(
        49,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 72 + 1,
    ),
    "City Trial: Break a CPU's machine 5 times or more in the city!": KARLocationData(
        50,
        "City Trial",
        "Purple Kirby: (X or Y button on Player Entry)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 76 + 1,
    ),
    "Stadium: DESTRUCTION DERBY 1 In one game, KO a rival 10 times or more!": KARLocationData(
        51,
        "Stadium: DESTRUCTION DERBY 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 80 + 1,
    ),
    "Stadium: DESTRUCTION DERBY 4 In one game, KO a rival 10 times or more!": KARLocationData(
        52,
        "Stadium: DESTRUCTION DERBY 4",
        "New Stadium: Destruction Derby 5",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 84 + 1,
    ),
    "Stadium: KIRBY MELEE 1 In one game, KO over 75 enemies by yourself!": KARLocationData(
        53,
        "Stadium: KIRBY MELEE 1",
        "New Stadium: Kirby Melee 2",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 88 + 1,
    ),
    "City Trial: Get 30 or more Glide Patches!": KARLocationData(
        54,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 92 + 1,
    ),
    "City Trial: In one game, eat 2 or more maxim tomatoes!": KARLocationData(
        55,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 96 + 1,
    ),
    "Stadium: DRAG RACE 2 Finish in less than 00:27:00 on Wagon Star!": KARLocationData(
        56,
        "Stadium: DRAG RACE 2",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 100 + 1,
    ),
    "Stadium: DRAG RACE 4 Finish in less than 00:33:00 on Turbo Star!": KARLocationData(
        57,
        "Stadium: DRAG RACE 4",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 104 + 1,
    ),
    "City Trial: Unlock Dragoon Parts A, B, and C on the Checklist!": KARLocationData(
        58,
        "City Trial",
        "Dragoon: Select in Free Run mode",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 108 + 1,
    ),
    "City Trial: In the city, bust Swerve Star while riding on Wheelie Bike!": KARLocationData(
        59,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 112 + 1,
    ),
    "City Trial: In the city, bust Rocket Star while riding on Slick Star!": KARLocationData(
        60,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 116 + 1,
    ),
    "City Trial: Pick up a total of over 100 items!": KARLocationData(
        61,
        "City Trial",
        "Sound Test: Item bounce",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 2,
    ),
    "City Trial: Free Run: Change Air Ride Machines 10 times or more!": KARLocationData(
        62,
        "City Trial: Free Run",
        "Sound Test: Legendary Air Ride Machine",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 4 + 2,
    ),
    "City Trial: Free Run: Drive for a total of 30 minutes or more!": KARLocationData(
        63,
        "City Trial: Free Run",
        "Sound Test: City Trial",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 8 + 2,
    ),
    "Stadium: DRAG RACE 1 Finish in less than 00:24:00!": KARLocationData(
        64,
        "Stadium: DRAG RACE 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 12 + 2,
    ),
    "Stadium: DRAG RACE 3 Finish in less than 00:35:00!": KARLocationData(
        65,
        "Stadium: DRAG RACE 3",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 16 + 2,
    ),
    "Stadium: HIGH JUMP Jump higher than 500 feet!": KARLocationData(
        66,
        "Stadium: HIGH JUMP",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 20 + 2,
    ),
    "Stadium: TARGET FLIGHT In one game, get exactly 90 points!": KARLocationData(
        67,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 24 + 2,
    ),
    "Stadium: TARGET FLIGHT get more than 1,500 points!": KARLocationData(
        68,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 28 + 2,
    ),
    "Stadium: AIR GLIDER stay airborne longer than 30 seconds!": KARLocationData(
        69,
        "Stadium: AIR GLIDER",
        "Sound Test: Air Glider",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 32 + 2,
    ),
    "Stadium: DESTRUCTION DERBY 4 In one game, KO your rivals 5 or more times!": KARLocationData(
        70,
        "Stadium: DESTRUCTION DERBY 4",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 36 + 2,
    ),
    "Stadium: DESTRUCTION DERBY (All) KO enemies over 150 times!": KARLocationData(
        71,
        "Stadium: DESTRUCTION DERBY ALL",
        "Hydra Part Y: Use 3 to complete Hydra",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 40 + 2,
    ),
    "Stadium: KIRBY MELEE (All) KO over 1,500 enemies!": KARLocationData(
        72,
        "Stadium: KIRBY MELEE ALL",
        "Hydra Part Z: Use 3 to complete Hydra",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 44 + 2,
    ),
    "City Trial: Break 5 or more of the huge pillars that appear!": KARLocationData(
        73,
        "City Trial",
        "Sound Test: Huge Pillar",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 48 + 2,
    ),
    "City Trial: Use up one of the restoration areas!": KARLocationData(
        74,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 52 + 2,
    ),
    "City Trial: Bust the star pole!": KARLocationData(
        75,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 56 + 2,
    ),
    "City Trial: Make your way to the garden in the sky!": KARLocationData(
        76,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 60 + 2,
    ),
    "City Trial: Use the grind rail to break into the crater!": KARLocationData(
        77,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 64 + 2,
    ),
    "City Trial: Get the Bomb ability from the Copy Chance Wheel!": KARLocationData(
        78,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 68 + 2,
    ),
    "City Trial: Have all players simultaneously get off of their machines!": KARLocationData(
        79,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 72 + 2,
    ),
    "City Trial: Enter a race with 3 CPU Players and do damage to all of them in the city!": KARLocationData(
        80,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 76 + 2,
    ),
    "City Trial: In one game, get 10 or more Top Speed Patches!": KARLocationData(
        81,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 80 + 2,
    ),
    "City Trial: In one game, get 10 or more Charge Patches!": KARLocationData(
        82,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 84 + 2,
    ),
    "City Trial: In one game, get 10 or more Defense Patches!": KARLocationData(
        83,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 88 + 2,
    ),
    "City Trial: Use Sensor Bombs to KO rivals 3 times or more!": KARLocationData(
        84,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 92 + 2,
    ),
    "City Trial: In one game, drink 3 or more energy drinks!": KARLocationData(
        85,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 96 + 2,
    ),
    "Stadium: DRAG RACE 2 Finish in less than 00:29:00 on Winged Star!": KARLocationData(
        86,
        "Stadium: DRAG RACE 2",
        "Brown Kirby:(X or Y button on player entry)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 100 + 2,
    ),
    "Stadium: DRAG RACE 4 Finish in less than 00:24:00 on Rex Wheelie!": KARLocationData(
        87,
        "Stadium: DRAG RACE 4",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 104 + 2,
    ),
    "City Trial: Unlock Hydra Parts X, Y, and Z on the Checklist!": KARLocationData(
        88,
        "City Trial",
        "Hydra: Select in Free Run mode",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 108 + 2,
    ),
    "City Trial: In the city, bust Warpstar while riding on Swerve Star!": KARLocationData(
        89,
        "City Trial",
        "Sound Test: The Lighthouse Light Burns",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 112 + 2,
    ),
    "City Trial: In the city, bust Turbo Star while riding on Rocket Star!": KARLocationData(
        90,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 116 + 2,
    ),
    "City Trial: pick up a total of over 500 items!": KARLocationData(
        91,
        "City Trial",
        "Bonus: Pause screen power-ups",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 3,
    ),
    "City Trial: break more than 500 boxes!": KARLocationData(
        92,
        "City Trial",
        "Sound test: dense fog today",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 4 + 3,
    ),
    "City Trial: Free Run: Drive for a total of 2 hours or more!": KARLocationData(
        93,
        "City Trial: Free Run",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 8 + 3,
    ),
    "Stadium: DRAG RACE 1 Finish in less than 00:20:00!": KARLocationData(
        94,
        "Stadium: DRAG RACE 1",
        "Sound Test: rowdy charge tank",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 12 + 3,
    ),
    "Stadium: DRAG RACE 3 Finish in less than 00:27:00!": KARLocationData(
        95,
        "Stadium: DRAG RACE 3",
        "New Stadium: Drag Race 4",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 16 + 3,
    ),
    "Stadium: HIGH JUMP Jump higher than 1,000 feet!": KARLocationData(
        96,
        "Stadium: HIGH JUMP",
        "Dragoon Part A: Use 3 to complete Dragoon",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 20 + 3,
    ),
    "Stadium: TARGET FLIGHT In one game, get a perfect score: 200 points!": KARLocationData(
        97,
        "Stadium: TARGET FLIGHT",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 24 + 3,
    ),
    "Stadium: AIR GLIDER fly more than 330 feet!": KARLocationData(
        98,
        "Stadium: AIR GLIDER",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 28 + 3,
    ),
    "Stadium: DESTRUCTION DERBY 1 In one game, KO your rivals 5 or more times!": KARLocationData(
        99,
        "Stadium: DESTRUCTION DERBY 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 32 + 3,
    ),
    "Stadium: DESTRUCTION DERBY 5 In one game, KO your rivals 5 or more times!": KARLocationData(
        100,
        "Stadium: DESTRUCTION DERBY 5",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 36 + 3,
    ),
    "Stadium: KIRBY MELEE 1 In one game, KO enemies over 50 times!": KARLocationData(
        101,
        "Stadium: KIRBY MELEE 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 40 + 3,
    ),
    "Stadium: VS. KING DEDEDE KO King Dedede in less than a minute!": KARLocationData(
        102,
        "Stadium: VS. KING DEDEDE",
        "King Dedede: Select in free run mode",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 44 + 3,
    ),
    "City Trial: Break a huge pillar within 40 seconds of the time it appears!": KARLocationData(
        103,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 48 + 3,
    ),
    "City Trial: Fill in over 100 Checklist blocks!": KARLocationData(
        104,
        "City Trial",
        "Ending: view with the A button",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 52 + 3,
    ),
    "City Trial: Bust the star pole 10 times or more!": KARLocationData(
        105,
        "City Trial",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 56 + 3,
    ),
    "City Trial: Open up the pitfall in the forest!": KARLocationData(
        106,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 60 + 3,
    ),
    "City Trial: Jump on top of the building 10 times or more using the super jump ramp!": KARLocationData(
        107,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 64 + 3,
    ),
    "City Trial: Get the Sleep ability from the Copy Chance Wheel!": KARLocationData(
        108,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 68 + 3,
    ),
    "City Trial: Let time run out while all players are off of their machines!": KARLocationData(
        109,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 72 + 3,
    ),
    "City Trial: In one game, get 50 or more items!": KARLocationData(
        110,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 76 + 3,
    ),
    "Stadium: DESTRUCTION DERBY 2 In one game, KO a rival 10 times or more!": KARLocationData(
        111,
        "Stadium: DESTRUCTION DERBY 2",
        "New Stadium: Destruction Derby 3",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 80 + 3,
    ),
    "Stadium: DESTRUCTION DERBY 5 In one game, KO a rival 10 times or more!": KARLocationData(
        112,
        "Stadium: DESTRUCTION DERBY 5",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 84 + 3,
    ),
    "Stadium: KIRBY MELEE 2 In one game, KO over 40 enemies by yourself!": KARLocationData(
        113,
        "Stadium: KIRBY MELEE 2",
        "Sound Test: Kirby Melee",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 88 + 3,
    ),
    "City Trial: Use Gold Spikes to KO rivals 3 times or more!": KARLocationData(
        114,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 92 + 3,
    ),
    "Stadium: DRAG RACE 1 Finish in less than 00:26:00 on Warpstar!": KARLocationData(
        115,
        "Stadium: DRAG RACE 1",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 96 + 3,
    ),
    "Stadium: DRAG RACE 3 Finish in less than 00:28:00 on Swerve Star!": KARLocationData(
        116,
        "Stadium: DRAG RACE 3",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 100 + 3,
    ),
    "City Trial: In one race, eat 3 or more plates of sushi!": KARLocationData(
        117,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 104 + 3,
    ),
    "City Trial: In the city, bust Wheelie Scooter while riding Compact Star!": KARLocationData(
        118,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 108 + 3,
    ),
    "City Trial: In the city, bust Formula Star while riding on Turbo Star!": KARLocationData(
        119,
        "City Trial",
        "None",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 112 + 3,
    ),
    "City Trial: In one match, complete both Dragoon and Hydra!": KARLocationData(
        120,
        "City Trial",
        "White Kirby:(X or Y button on player entry)",
        KARLocationType.CHECKLISTBOX,
        CITY_TRIAL_BASE_CHECKLIST_ADDRESS + 116 + 3,
    ),
}

AIR_RIDE_LOCATION_TABLE: dict[str, KARLocationData] = {
    "Air Ride: Race over 100 laps!": KARLocationData(
        121,
        "Air Ride",
        "New Course: Nebula Belt",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS,
    ),
    "Air Ride: Defeat over 300 of your enemies!": KARLocationData(
        122,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 4,
    ),
    "Air Ride: Swallow Sword Knight (sword-wielding enemy) 3 time or more and take 1st place!": KARLocationData(
        123,
        "Air Ride",
        "Green Kirby: (X or Y Button on Player Entry)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 8,
    ),
    "Air Ride: MAGMA FLOWS Race over 4,800 feet in 2 minutes!": KARLocationData(
        124,
        "Air Ride: MAGMA FLOWS",
        "Sound Test: MAGMA FLOWS",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 12,
    ),
    "Air Ride: Swallow 5 consecutive garbage enemies (with no copy abilities) and take 1st!!": KARLocationData(
        125,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 16,
    ),
    "Air Ride: FANTASY MEADOWS Race over 4,500 feet in 2 minutes!": KARLocationData(
        126,
        "Air Ride: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 20,
    ),
    "Air Ride: Fill in over 100 Checklist blocks!": KARLocationData(
        127,
        "Air Ride",
        "Ending: View with the A button",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 24,
    ),
    "Air Ride: Sword Challenge: During a race, swing your sword exactly 10 times and take 1st!": KARLocationData(
        128,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 28,
    ),
    "Air Ride: Hit 20 or more rivals with your Quick Spin!": KARLocationData(
        129,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 32,
    ),
    "Air Ride: CELESTIAL VALLEY Finish 2 laps in under 01:56:00!": KARLocationData(
        130,
        "Air Ride: CELESTIAL VALLEY",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 36,
    ),
    "Air Ride: BEANSTALK PARK Finish 2 laps in under 01:56:00!": KARLocationData(
        131,
        "Air Ride: BEANSTALK PARK",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 40,
    ),
    "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:00:00!": KARLocationData(
        132,
        "Time Attack: FANTASY MEADOWS",
        "Music: Meadows (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 44,
    ),
    "Air Ride: Time Attack: SKY SANDS Finish in under 02:40:00!": KARLocationData(
        133,
        "Time Attack: SKY SANDS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 48,
    ),
    "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:04:00!": KARLocationData(
        134,
        "Time Attack: MAGMA FLOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 52,
    ),
    "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 02:48:00!": KARLocationData(
        135,
        "Time Attack: MACHINE PASSAGE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 56,
    ),
    "Air Ride: Free Run: FANTASY MEADOWS Finish 1 lap in under 00:21:00!": KARLocationData(
        136,
        "Free Run: FANTASY MEADOWS",
        "Sound Test: FANTASY MEADOWS",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 60,
    ),
    "Air Ride: Free Run: CELESTIAL VALLEY Do 1 lap under 01:02:00 on Slick Star!": KARLocationData(
        137,
        "Free Run: CELESTIAL VALLEY",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 64,
    ),
    "Air Ride: Free Run: FROZEN HILLSIDE Finish 1 lap in under 01:10:00!": KARLocationData(
        138,
        "Free Run: FROZEN HILLSIDE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 68,
    ),
    "Air Ride: Free Run: MAGMA FLOWS Finish 1 lap in under 01:01:00!": KARLocationData(
        139,
        "Free Run: MAGMA FLOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 72,
    ),
    "Air Ride: Free Run: BEANSTALK PARK Do 1 lap under 00:58:00 on Winged Star!": KARLocationData(
        140,
        "Free Run: BEANSTALK PARK",
        "Sound Test: BEANSTALK PARK",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 76,
    ),
    "Air Ride: Free Run: CHECKER KNIGHTS Finish 1 lap in under 01:35:00!": KARLocationData(
        141,
        "Free Run: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 80,
    ),
    "Air Ride: Race all of the standard Air Ride courses!": KARLocationData(
        142,
        "Air Ride",
        "New Machine: WHEELIE BIKE",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 84,
    ),
    "Air Ride: Finish in 1st place while flying through the air!": KARLocationData(
        143,
        "Air Ride",
        "New Machine: WINGED STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 88,
    ),
    "Air Ride: Finish in 1st place with Wing ability!": KARLocationData(
        144,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 92,
    ),
    "Air Ride: FANTASY MEADOWS: Race 1 lap without dropping below 20 mph!": KARLocationData(
        145,
        "Air Ride: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 96,
    ),
    "Air Ride: CHECKER KNIGHTS: Break at least 2 walls and finish in 1st place!": KARLocationData(
        146,
        "Air Ride: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 100,
    ),
    "Air Ride: SKY SANDS: Enter the quicksand 3 times and finish in 1st place!": KARLocationData(
        147,
        "Air Ride: SKY SANDS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 104,
    ),
    "Air Ride: Time Attack: SKY SANDS Finish in under 02:40:00 on Wagon Star!": KARLocationData(
        148,
        "Time Attack: SKY SANDS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 108,
    ),
    "Air Ride: MAGMA FLOWS: Use all of the Boost Panels and finish in 1st place!": KARLocationData(
        149,
        "Air Ride: MAGMA FLOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 112,
    ),
    "Air Ride: CELESTIAL VALLEY: Use the Copy Chance Wheel on top of the tree!": KARLocationData(
        150,
        "Air Ride: CELESTIAL VALLEY",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 116,
    ),
    "Air Ride: Race over 300 laps!": KARLocationData(
        151,
        "Air Ride",
        "Music: Nebula (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 1,
    ),
    "Air Ride: Defeat over 1,000 of your enemies!": KARLocationData(
        152,
        "Air Ride",
        "KING DEDEDE: Available on normal courses",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 4 + 1,
    ),
    "Air Ride: Swallow Wheelie (motorcycle enemy) 3 times or more and take 1st place!": KARLocationData(
        153,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 8 + 1,
    ),
    "Air Ride: MAGMA FLOWS Finish 2 laps in under 02:20:00!": KARLocationData(
        154,
        "Air Ride: MAGMA FLOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 12 + 1,
    ),
    "Air Ride: BEANSTALK PARK Finish 2 laps in under 02:18:00!": KARLocationData(
        155,
        "Air Ride: BEANSTALK PARK",
        "Purple Kirby: (X or Y Button on Player Entry)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 16 + 1,
    ),
    "Air Ride: CELESTIAL VALLEY Race over 6,000 feet in 2 minutes!": KARLocationData(
        156,
        "Air Ride: CELESTIAL VALLEY",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 20 + 1,
    ),
    "Air Ride: FANTASY MEADOWS Finish 3 laps in under 01:20:00!": KARLocationData(
        157,
        "Air Ride: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 24 + 1,
    ),
    "Air Ride: FROZEN HILLSIDE Race 2 laps in under 02:20:00!": KARLocationData(
        158,
        "Air Ride: FROZEN HILLSIDE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 28 + 1,
    ),
    "Air Ride: MACHINE PASSAGE Race over 4,500 feet in 2 minutes!": KARLocationData(
        159,
        "Air Ride: MACHINE PASSAGE",
        "New Machine: JET STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 32 + 1,
    ),
    "Air Ride: SKY SANDS Finish 2 laps in under 01:45:00!": KARLocationData(
        160,
        "Air Ride: SKY SANDS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 36 + 1,
    ),
    "Air Ride: MACHINE PASSAGE Finish 2 laps in under 01:48:00!": KARLocationData(
        161,
        "Air Ride: MACHINE PASSAGE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 40 + 1,
    ),
    "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 03:20:00!": KARLocationData(
        162,
        "Time Attack: CELESTIAL VALLEY",
        "New Machine: BULK STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 44 + 1,
    ),
    "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 03:14:00!": KARLocationData(
        163,
        "Time Attack: FROZEN HILLSIDE",
        "New Machine: FORMULA STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 48 + 1,
    ),
    "Air Ride: Time Attack: BEANSTALK PARK Finish in under 03:10:00!": KARLocationData(
        164,
        "Time Attack: BEANSTALK PARK",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 52 + 1,
    ),
    "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 04:30:00!": KARLocationData(
        165,
        "Time Attack: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 56 + 1,
    ),
    "Air Ride: Free Run: FANTASY MEADOWS Do 1 lap under 00:23:00 on Wagon Star!": KARLocationData(
        166,
        "Free Run: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 60 + 1,
    ),
    "Air Ride: Free Run: SKY SANDS Finish 1 lap in under 01:05:00!": KARLocationData(
        167,
        "Free Run: SKY SANDS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 64 + 1,
    ),
    "Air Ride: Free Run: FROZEN HILLSIDE Finish 1 lap in under 00:58:00!": KARLocationData(
        168,
        "Free Run: FROZEN HILLSIDE",
        "Sound Test: FROZEN HILLSIDE",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 68 + 1,
    ),
    "Air Ride: Free Run: MAGMA FLOWS Do 1 lap under 01:02:00 on Turbo Star!": KARLocationData(
        169,
        "Free Run: MAGMA FLOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 72 + 1,
    ),
    "Air Ride: Free Run: MACHINE PASSAGE Finish 1 lap in under 01:05:00!": KARLocationData(
        170,
        "Free Run: MACHINE PASSAGE",
        "New Machine: ROCKET STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 76 + 1,
    ),
    "Air Ride: Free Run: CHECKER KNIGHTS Finish 1 lap in under 01:20:00!": KARLocationData(
        171,
        "Free Run: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 80 + 1,
    ),
    "Air Ride: Start the final lap in 4th place and move to 1st to win.": KARLocationData(
        172,
        "Air Ride",
        "New Machine: WHEELIE SCOOTER",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 84 + 1,
    ),
    "Air Ride: Finish in 1st place with Sleep ability!": KARLocationData(
        173,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 88 + 1,
    ),
    "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:05:00 on Slick Star!": KARLocationData(
        174,
        "Time Attack: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 92 + 1,
    ),
    "Air Ride: BEANSTALK PARK: Race over 3 laps without riding the Ferris wheel!": KARLocationData(
        175,
        "Air Ride: BEANSTALK PARK",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 96 + 1,
    ),
    "Air Ride: CHECKER KNIGHTS: Swallow over 20 enemies and finish in 1st place!": KARLocationData(
        176,
        "Air Ride: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 100 + 1,
    ),
    "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 02:58:00 on Jet Star!": KARLocationData(
        177,
        "Time Attack: CELESTIAL VALLEY",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 104 + 1,
    ),
    "Air Ride: MACHINE PASSAGE: Finish in 1st place without touching the walls even once!": KARLocationData(
        178,
        "Air Ride: MACHINE PASSAGE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 108 + 1,
    ),
    "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 03:10:00 on Turbo Star!": KARLocationData(
        179,
        "Time Attack: FROZEN HILLSIDE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 112 + 1,
    ),
    "Air Ride: Time Attack: BEANSTALK PARK Finish in under 03:00:00 on Rocket Star!": KARLocationData(
        180,
        "Time Attack: BEANSTALK PARK",
        "Sound Test: NEBULA BELT",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 116 + 1,
    ),
    "Air Ride: Glide for more than 30 minutes!": KARLocationData(
        181,
        "Air Ride",
        "META KNIGHT: Available on normal courses",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 2,
    ),
    "Air Ride: Swallow Chilly (snowman enemy) 3 or more times and take 1st place!": KARLocationData(
        182,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 4 + 2,
    ),
    "Air Ride: In any mode other than Free Run, reach the goal a total of 3 times!": KARLocationData(
        183,
        "Air Ride",
        "New Machine: WAGON STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 8 + 2,
    ),
    "Air Ride: Swallow 200 or more enemies!": KARLocationData(
        184,
        "Air Ride",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 12 + 2,
    ),
    "Air Ride: MACHINE PASSAGE Finish 2 laps in under 02:10:00!": KARLocationData(
        185,
        "Air Ride: MACHINE PASSAGE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 16 + 2,
    ),
    "Air Ride: SKY SANDS Race over 4,000 feet in 2 minutes!": KARLocationData(
        186,
        "Air Ride: SKY SANDS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 20 + 2,
    ),
    "Air Ride: CELESTIAL VALLEY Finish 2 laps in under 02:20:00!": KARLocationData(
        187,
        "Air Ride: CELESTIAL VALLEY",
        "White Kirby: (X or Y button on Player Entry)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 24 + 2,
    ),
    "Air Ride: Tornado Challenge: Defeat over 15 enemies as Tornado Kirby and finish in 1st place!": KARLocationData(
        188,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 28 + 2,
    ),
    "Air Ride: BEANSTALK PARK Race over 5,500 feet in 2 minutes!": KARLocationData(
        189,
        "Air Ride: BEANSTALK PARK",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 32 + 2,
    ),
    "Air Ride: FROZEN HILLSIDE Finish 2 laps in under 01:56:00!": KARLocationData(
        190,
        "Air Ride: FROZEN HILLSIDE",
        "Music: Hillside (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 36 + 2,
    ),
    "Air Ride: CHECKER KNIGHTS Finish 2 laps in under 02:40:00!": KARLocationData(
        191,
        "Air Ride: CHECKER KNIGHTS",
        "Sound Test: CHECKER KNIGHTS",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 40 + 2,
    ),
    "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 02:56:00!": KARLocationData(
        192,
        "Time Attack: CELESTIAL VALLEY",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 44 + 2,
    ),
    "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 02:50:00!": KARLocationData(
        193,
        "Time Attack: FROZEN HILLSIDE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 48 + 2,
    ),
    "Air Ride: Time Attack: BEANSTALK PARK Finish in under 02:55:00!": KARLocationData(
        194,
        "Time Attack: BEANSTALK PARK",
        "Music: Beanstalk (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 52 + 2,
    ),
    "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 04:00:00!": KARLocationData(
        195,
        "Time Attack: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 56 + 2,
    ),
    "Air Ride: Free Run: CELESTIAL VALLEY Finish 1 lap in under 01:10:00!": KARLocationData(
        196,
        "Free Run: CELESTIAL VALLEY",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 60 + 2,
    ),
    "Air Ride: Free Run: SKY SANDS Finish 1 lap in under 00:53:00!": KARLocationData(
        197,
        "Free Run: SKY SANDS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 64 + 2,
    ),
    "Air Ride: Free Run: FROZEN HILLSIDE Do 1 lap under 01:10:00 on Formula Star!": KARLocationData(
        198,
        "Free Run: FROZEN HILLSIDE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 68 + 2,
    ),
    "Air Ride: Free Run: BEANSTALK PARK Finish 1 lap in under 01:07:00!": KARLocationData(
        199,
        "Free Run: BEANSTALK PARK",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 72 + 2,
    ),
    "Air Ride: Free Run: MACHINE PASSAGE Finish 1 lap in under 00:56:00!": KARLocationData(
        200,
        "Free Run: MACHINE PASSAGE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 76 + 2,
    ),
    "Air Ride: Free Run: CHECKER KNIGHTS Do 1 lap under 01:25:00 on Rocket Star!": KARLocationData(
        201,
        "Free Run: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 80 + 2,
    ),
    "Air Ride: Cross the finish line while spinning and take 1st place!": KARLocationData(
        202,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 84 + 2,
    ),
    "Air Ride: Finish in 1st place with Fire ability!": KARLocationData(
        203,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 88 + 2,
    ),
    "Air Ride: In one game, drop from the cliffs 3 times!": KARLocationData(
        204,
        "Air Ride",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 92 + 2,
    ),
    "Air Ride: BEANSTALK PARK: Swallow over 20 enemies and take 1st place!": KARLocationData(
        205,
        "Air Ride: BEANSTALK PARK",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 96 + 2,
    ),
    "Air Ride: FROZEN HILLSIDE: Split at least 20 ice platforms and finish in 1st place!": KARLocationData(
        206,
        "Air Ride: FROZEN HILLSIDE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 100 + 2,
    ),
    "Air Ride: SKY SANDS: Open the trapdoor exactly 3 times and finish in 1st place!": KARLocationData(
        207,
        "Air Ride: SKY SANDS",
        "Music: Sky Sands (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 104 + 2,
    ),
    "Air Ride: MAGMA FLOWS: Use all the volcano rails and finish in 1st place!": KARLocationData(
        208,
        "Air Ride: MAGMA FLOWS",
        "New Machine: TURBO STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 108 + 2,
    ),
    "Air Ride: CELESTIAL VALLEY: Over one race, ride on both the left and right bridge railings!": KARLocationData(
        209,
        "Air Ride: CELESTIAL VALLEY",
        "Music: Celestial (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 112 + 2,
    ),
    "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 02:50:00 on Rex Wheelie!": KARLocationData(
        210,
        "Time Attack: MACHINE PASSAGE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 116 + 2,
    ),
    "Air Ride: Glide for more than 1 hour!": KARLocationData(
        211,
        "Air Ride",
        "Bonus Movie: Special machine intros",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 3,
    ),
    "Air Ride: Swallow Plasma Wisp (electrical enemy) 3 or more times and take 1st place!": KARLocationData(
        212,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 4 + 3,
    ),
    "Air Ride: CHECKER KNIGHTS Race over 5,500 feet in 2 minutes!": KARLocationData(
        213,
        "Air Ride: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 8 + 3,
    ),
    "Air Ride: Defeat 100 or more enemies with exhaled stars!": KARLocationData(
        214,
        "Air Ride",
        "New Machine: REX WHEELIE",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 12 + 3,
    ),
    "Air Ride: CHECKER KNIGHTS Finish 2 laps in under 03:05:00!": KARLocationData(
        215,
        "Air Ride: CHECKER KNIGHTS",
        "New Machine: SLICK STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 16 + 3,
    ),
    "Air Ride: FROZEN HILLSIDE Race over 5,300 feet in 2 minutes!": KARLocationData(
        216,
        "Air Ride: FROZEN HILLSIDE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 20 + 3,
    ),
    "Air Ride: SKY SANDS Finish 2 laps in under 02:05:00!": KARLocationData(
        217,
        "Air Ride: SKY SANDS",
        "New Machine: SWERVE STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 24 + 3,
    ),
    "Air Ride: Defeat 10 or more enemies using the Quick Spin!": KARLocationData(
        218,
        "Air Ride",
        "New Machine: SHADOW STAR",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 28 + 3,
    ),
    "Air Ride: FANTASY MEADOWS Finish 3 laps in under 01:03:00!": KARLocationData(
        219,
        "Air Ride: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 32 + 3,
    ),
    "Air Ride: MAGMA FLOWS Finish 2 laps in under 02:01:00!": KARLocationData(
        220,
        "Air Ride: MAGMA FLOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 36 + 3,
    ),
    "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:12:00!": KARLocationData(
        221,
        "Time Attack: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 40 + 3,
    ),
    "Air Ride: Time Attack: SKY SANDS Finish in under 03:10:00!": KARLocationData(
        222,
        "Time Attack: SKY SANDS",
        "Sound Test: SKY SANDS",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 44 + 3,
    ),
    "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:20:00!": KARLocationData(
        223,
        "Time Attack: MAGMA FLOWS",
        "Music: Magma (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 48 + 3,
    ),
    "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 03:10:00!": KARLocationData(
        224,
        "Time Attack: MACHINE PASSAGE",
        "Sound Test: MACHINE PASSAGE",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 52 + 3,
    ),
    "Air Ride: Free Run: FANTASY MEADOWS Finish 1 lap in under 00:24:00!": KARLocationData(
        225,
        "Free Run: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 56 + 3,
    ),
    "Air Ride: Free Run: CELESTIAL VALLEY Finish 1 lap in under 00:57:00!": KARLocationData(
        226,
        "Free Run: CELESTIAL VALLEY",
        "Sound Test: CELESTIAL VALLEY",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 60 + 3,
    ),
    "Air Ride: Free Run: SKY SANDS Do 1 lap under 01:05:00 on Bulk Star!": KARLocationData(
        227,
        "Free Run: SKY SANDS",
        "Brown Kirby: (X or Y Button on Player Entry)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 64 + 3,
    ),
    "Air Ride: Free Run: MAGMA FLOWS Finish 1 lap in under 01:10:00!": KARLocationData(
        228,
        "Free Run: MAGMA FLOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 68 + 3,
    ),
    "Air Ride: Free Run: BEANSTALK PARK Finish 1 lap in under 00:58:00!": KARLocationData(
        229,
        "Free Run: BEANSTALK PARK",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 72 + 3,
    ),
    "Air Ride: Free Run: MACHINE PASSAGE Do 1 lap under 00:57:00 on Swerve Star!": KARLocationData(
        230,
        "Free Run: MACHINE PASSAGE",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 76 + 3,
    ),
    "Air Ride: Make your lap time's last two digits the same!": KARLocationData(
        231,
        "Air Ride",
        "Sound Test: Results Screen",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 80 + 3,
    ),
    "Air Ride: Finish in 1st place while taking damage!": KARLocationData(
        232,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 84 + 3,
    ),
    "Air Ride: Finish in 1st place with Needle ability!": KARLocationData(
        233,
        "Air Ride",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 88 + 3,
    ),
    "Air Ride: FANTASY MEADOWS: Swallow over 20 enemies and take 1st place!": KARLocationData(
        234,
        "Air Ride: FANTASY MEADOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 92 + 3,
    ),
    "Air Ride: CHECKER KNIGHTS: Use spin panels 7 times or more and take 1st place!": KARLocationData(
        235,
        "Air Ride: CHECKER KNIGHTS",
        "Music: Checker (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 96 + 3,
    ),
    "Air Ride: SKY SANDS: Break all of the coral and finish in 1st place!": KARLocationData(
        236,
        "Air Ride: SKY SANDS",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 100 + 3,
    ),
    "Air Ride: MACHINE PASSAGE: Shoot 3 characters out of the cannon at one time!": KARLocationData(
        237,
        "Air Ride: MACHINE PASSAGE",
        "Music: Machine (X or Y Button on Select Course)",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 104 + 3,
    ),
    "Air Ride: MAGMA FLOWS: Bump into a flaming dragon!": KARLocationData(
        238,
        "Air Ride: MAGMA FLOWS",
        "Check off an empty box of your choice!",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 108 + 3,
    ),
    "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:15:00 on Shadow Star!": KARLocationData(
        239,
        "Time Attack: MAGMA FLOWS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 112 + 3,
    ),
    "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 03:55:00 on Warpstar!": KARLocationData(
        240,
        "Time Attack: CHECKER KNIGHTS",
        "None",
        KARLocationType.CHECKLISTBOX,
        AIR_RIDE_BASE_CHECKLIST_ADDRESS + 116 + 3,
    ),
}


LOCATION_LOOKUP_ID_TO_NAME: dict[int, str] = {
    location_data.code: location_name
    for location_name, location_data in (CITY_TRIAL_LOCATION_TABLE | AIR_RIDE_LOCATION_TABLE).items()
    if location_data.code is not None
}

location_name_groups = {
    "City Trial: Stadiums": {
        "Stadium: play in over 10 stadium modes!",
        "Stadium: DRAG RACE 2 Finish in less than 00:24:00!",
        "Stadium: DRAG RACE 4 Finish in less than 00:24:00!",
        "Stadium: HIGH JUMP Stay airborne longer than 10 seconds!",
        "Stadium: TARGET FLIGHT stay airborne longer than 15 seconds!",
        "Stadium: AIR GLIDER fly more than 660 feet!",
        "Stadium: DESTRUCTION DERBY 2 In one game, KO your rivals 5 or more times!",
        "Stadium: DESTRUCTION DERBY 1 bust all the rocks on the field!",
        "Stadium: KIRBY MELEE 2 In one game, KO enemies over 30 times!",
        "Stadium: DRAG RACE 1 Finish in less than 00:17:00 on Formula Star!",
        "Stadium: DRAG RACE 3 Finish in less than 00:31:00 on Wheelie Bike!",
        "Stadium: play in over 20 stadium modes!",
        "Stadium: DRAG RACE 2 Finish in less than 00:20:00!",
        "Stadium: DRAG RACE 4 Finish in less than 00:19:00!",
        "Stadium: TARGET FLIGHT In one game, get over 150 points!",
        "Stadium: TARGET FLIGHT play 15 times or more!",
        "Stadium: AIR GLIDER fly more than 1,300 feet!",
        "Stadium: DESTRUCTION DERBY 3 In one game, KO your rivals 5 or more times!",
        "Stadium: DESTRUCTION DERBY (All) KO enemies over 50 times!",
        "Stadium: KIRBY MELEE (All) KO over 500 enemies!",
        "Stadium: DESTRUCTION DERBY 1 In one game, KO a rival 10 times or more!",
        "Stadium: DESTRUCTION DERBY 4 In one game, KO a rival 10 times or more!",
        "Stadium: KIRBY MELEE 1 In one game, KO over 75 enemies by yourself!",
        "Stadium: DRAG RACE 2 Finish in less than 00:27:00 on Wagon Star!",
        "Stadium: DRAG RACE 4 Finish in less than 00:33:00 on Turbo Star!",
        "Stadium: DRAG RACE 1 Finish in less than 00:24:00!",
        "Stadium: DRAG RACE 3 Finish in less than 00:35:00!",
        "Stadium: HIGH JUMP Jump higher than 500 feet!",
        "Stadium: TARGET FLIGHT In one game, get exactly 90 points!",
        "Stadium: TARGET FLIGHT get more than 1,500 points!",
        "Stadium: AIR GLIDER stay airborne longer than 30 seconds!",
        "Stadium: DESTRUCTION DERBY 4 In one game, KO your rivals 5 or more times!",
        "Stadium: DESTRUCTION DERBY (All) KO enemies over 150 times!",
        "Stadium: KIRBY MELEE (All) KO over 1,500 enemies!",
        "Stadium: DRAG RACE 2 Finish in less than 00:29:00 on Winged Star!",
        "Stadium: DRAG RACE 4 Finish in less than 00:24:00 on Rex Wheelie!",
        "Stadium: DRAG RACE 1 Finish in less than 00:20:00!",
        "Stadium: DRAG RACE 3 Finish in less than 00:27:00!",
        "Stadium: HIGH JUMP Jump higher than 1,000 feet!",
        "Stadium: TARGET FLIGHT In one game, get a perfect score: 200 points!",
        "Stadium: AIR GLIDER fly more than 330 feet!",
        "Stadium: DESTRUCTION DERBY 1 In one game, KO your rivals 5 or more times!",
        "Stadium: DESTRUCTION DERBY 5 In one game, KO your rivals 5 or more times!",
        "Stadium: KIRBY MELEE 1 In one game, KO enemies over 50 times!",
        "Stadium: VS. KING DEDEDE KO King Dedede in less than a minute!",
        "Stadium: DESTRUCTION DERBY 2 In one game, KO a rival 10 times or more!",
        "Stadium: DESTRUCTION DERBY 5 In one game, KO a rival 10 times or more!",
        "Stadium: KIRBY MELEE 2 In one game, KO over 40 enemies by yourself!",
        "Stadium: DRAG RACE 1 Finish in less than 00:26:00 on Warpstar!",
        "Stadium: DRAG RACE 3 Finish in less than 00:28:00 on Swerve Star!",
    },
    "City Trial: Free Run": {
        "City Trial: Free Run: Drive for a total of 2 hours or more!",
        "City Trial: Free Run: Drive for a total of 30 minutes or more!",
        "City Trial: Free Run: Drive for a total of 10 minutes or more!",
        "City Trial: Free Run: Change Air Ride Machines 10 times or more!",
    },
    "City Trial: Multiplayer": {
        "City Trial: Let time run out while all players are on the rails!",
        "City Trial: Have all players simultaneously get off of their machines!",
        "City Trial: Let time run out while all players are off of their machines!",
    },
    "City Trial: CPUs": {
        "City Trial: Break a CPU's machine 5 times or more in the city!",
        "City Trial: Enter a race with 3 CPU Players and do damage to all of them in the city!",
        "City Trial: Do damage to a rival within the first 10 seconds of a match!",
    },
    "City Trial: Bust Vehicle on Vehicle": {
        "City Trial: In the city, bust Wheelie Bike while riding on Warpstar!",
        "City Trial: In the city, bust Slick Star while riding on Formula Star!",
        "City Trial: In the city, bust Swerve Star while riding on Wheelie Bike!",
        "City Trial: In the city, bust Rocket Star while riding on Slick Star!",
        "City Trial: In the city, bust Warpstar while riding on Swerve Star!",
        "City Trial: In the city, bust Turbo Star while riding on Rocket Star!",
        "City Trial: In the city, bust Wheelie Scooter while riding Compact Star!",
        "City Trial: In the city, bust Formula Star while riding on Turbo Star!",
    },
    "City Trial: Events": {
        "City Trial: Use up one of the restoration areas!",
        "City Trial: The meteor attacks the city 3 or more times!",
        "City Trial: Do some damage to Dyna Blade!",
        "City Trial: Get trampled by Dyna Blade!",
        "City Trial: Steal over 8 items from Tac by yourself!",
    },
    "City Trial: Patches": {
        "City Trial: In one game, get over 10 Boost Patches!",
        "City Trial: In one game, get 10 or more Turn Patches!",
        "City Trial: In one game, get 10 or more Weight Patches!",
        "City Trial: In one game, get 10 or more Glide Patches!",
        "City Trial: Get 30 or more Glide Patches!",
        "City Trial: In one game, get 10 or more Top Speed Patches!",
        "City Trial: In one game, get 10 or more Charge Patches!",
        "City Trial: In one game, get 10 or more Defense Patches!",
    },
    "City Trial: High Effort": {
        "City Trial: break more than 500 boxes!",
        "City Trial: break more than 1000 boxes!",
        "City Trial: pick up a total of over 1000 items!",
        "City Trial: Pick up a total of over 3000 items!",
        "City Trial: Free Run: Drive for a total of 2 hours or more!",
        "City Trial: Free Run: Drive for a total of 30 minutes or more!",
        "City Trial: Free Run: Drive for a total of 10 minutes or more!",
        "City Trial: In one match, complete both Dragoon and Hydra!",
        "City Trial: Fill in over 100 Checklist blocks!",
    },
    "Air Ride: Races": {
        "Air Ride: MAGMA FLOWS Race over 4,800 feet in 2 minutes!",
        "Air Ride: Swallow 5 consecutive garbage enemies (with no copy abilities) and take 1st!!",
        "Air Ride: FANTASY MEADOWS Race over 4,500 feet in 2 minutes!",
        "Air Ride: CELESTIAL VALLEY Finish 2 laps in under 01:56:00!",
        "Air Ride: BEANSTALK PARK Finish 2 laps in under 01:56:00!",
        "Air Ride: Finish in 1st place while flying through the air!",
        "Air Ride: Finish in 1st place with Wing ability!",
        "Air Ride: MAGMA FLOWS Finish 2 laps in under 02:20:00!",
        "Air Ride: BEANSTALK PARK Finish 2 laps in under 02:18:00!",
        "Air Ride: CELESTIAL VALLEY Race over 6,000 feet in 2 minutes!",
        "Air Ride: FANTASY MEADOWS Finish 3 laps in under 01:20:00!",
        "Air Ride: FROZEN HILLSIDE Race 2 laps in under 02:20:00!",
        "Air Ride: MACHINE PASSAGE Race over 4,500 feet in 2 minutes!",
        "Air Ride: SKY SANDS Finish 2 laps in under 01:45:00!",
        "Air Ride: MACHINE PASSAGE Finish 2 laps in under 01:48:00!",
        "Air Ride: Start the final lap in 4th place and move to 1st to win.",
        "Air Ride: Finish in 1st place with Sleep ability!",
        "Air Ride: MACHINE PASSAGE Finish 2 laps in under 02:10:00!",
        "Air Ride: SKY SANDS Race over 4,000 feet in 2 minutes!",
        "Air Ride: CELESTIAL VALLEY Finish 2 laps in under 02:20:00!",
        "Air Ride: BEANSTALK PARK Race over 5,500 feet in 2 minutes!",
        "Air Ride: FROZEN HILLSIDE Finish 2 laps in under 01:56:00!",
        "Air Ride: CHECKER KNIGHTS Finish 2 laps in under 02:40:00!",
        "Air Ride: Cross the finish line while spinning and take 1st place!",
        "Air Ride: Finish in 1st place with Fire ability!",
        "Air Ride: CHECKER KNIGHTS Race over 5,500 feet in 2 minutes!",
        "Air Ride: CHECKER KNIGHTS Finish 2 laps in under 03:05:00!",
        "Air Ride: FROZEN HILLSIDE Race over 5,300 feet in 2 minutes!",
        "Air Ride: SKY SANDS Finish 2 laps in under 02:05:00!",
        "Air Ride: FANTASY MEADOWS Finish 3 laps in under 01:03:00!",
        "Air Ride: MAGMA FLOWS Finish 2 laps in under 02:01:00!",
        "Air Ride: Finish in 1st place while taking damage!",
        "Air Ride: Finish in 1st place with Needle ability!",
    },
    "Air Ride: Free Run": {
        "Air Ride: Free Run: FANTASY MEADOWS Finish 1 lap in under 00:21:00!",
        "Air Ride: Free Run: CELESTIAL VALLEY Do 1 lap under 01:02:00 on Slick Star!",
        "Air Ride: Free Run: FROZEN HILLSIDE Finish 1 lap in under 01:10:00!",
        "Air Ride: Free Run: MAGMA FLOWS Finish 1 lap in under 01:01:00!",
        "Air Ride: Free Run: BEANSTALK PARK Do 1 lap under 00:58:00 on Winged Star!",
        "Air Ride: Free Run: CHECKER KNIGHTS Finish 1 lap in under 01:35:00!",
        "Air Ride: Free Run: FANTASY MEADOWS Do 1 lap under 00:23:00 on Wagon Star!",
        "Air Ride: Free Run: SKY SANDS Finish 1 lap in under 01:05:00!",
        "Air Ride: Free Run: FROZEN HILLSIDE Finish 1 lap in under 00:58:00!",
        "Air Ride: Free Run: MAGMA FLOWS Do 1 lap under 01:02:00 on Turbo Star!",
        "Air Ride: Free Run: MACHINE PASSAGE Finish 1 lap in under 01:05:00!",
        "Air Ride: Free Run: CHECKER KNIGHTS Finish 1 lap in under 01:20:00!",
        "Air Ride: Free Run: CELESTIAL VALLEY Finish 1 lap in under 01:10:00!",
        "Air Ride: Free Run: SKY SANDS Finish 1 lap in under 00:53:00!",
        "Air Ride: Free Run: FROZEN HILLSIDE Do 1 lap under 01:10:00 on Formula Star!",
        "Air Ride: Free Run: BEANSTALK PARK Finish 1 lap in under 01:07:00!",
        "Air Ride: Free Run: MACHINE PASSAGE Finish 1 lap in under 00:56:00!",
        "Air Ride: Free Run: CHECKER KNIGHTS Do 1 lap under 01:25:00 on Rocket Star!",
        "Air Ride: Free Run: FANTASY MEADOWS Finish 1 lap in under 00:24:00!",
        "Air Ride: Free Run: CELESTIAL VALLEY Finish 1 lap in under 00:57:00!",
        "Air Ride: Free Run: SKY SANDS Do 1 lap under 01:05:00 on Bulk Star!",
        "Air Ride: Free Run: MAGMA FLOWS Finish 1 lap in under 01:10:00!",
        "Air Ride: Free Run: BEANSTALK PARK Finish 1 lap in under 00:58:00!",
        "Air Ride: Free Run: MACHINE PASSAGE Do 1 lap under 00:57:00 on Swerve Star!",
    },
    "Air Ride: Time Attack": {
        "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:00:00!",
        "Air Ride: Time Attack: SKY SANDS Finish in under 02:40:00!",
        "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:04:00!",
        "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 02:48:00!",
        "Air Ride: Time Attack: SKY SANDS Finish in under 02:40:00 on Wagon Star!",
        "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 03:20:00!",
        "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 03:14:00!",
        "Air Ride: Time Attack: BEANSTALK PARK Finish in under 03:10:00!",
        "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 04:30:00!",
        "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:05:00 on Slick Star!",
        "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 02:58:00 on Jet Star!",
        "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 03:10:00 on Turbo Star!",
        "Air Ride: Time Attack: BEANSTALK PARK Finish in under 03:00:00 on Rocket Star!",
        "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 02:56:00!",
        "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 02:50:00!",
        "Air Ride: Time Attack: BEANSTALK PARK Finish in under 02:55:00!",
        "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 04:00:00!",
        "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 02:50:00 on Rex Wheelie!",
        "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:12:00!",
        "Air Ride: Time Attack: SKY SANDS Finish in under 03:10:00!",
        "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:20:00!",
        "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 03:10:00!",
        "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:15:00 on Shadow Star!",
        "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 03:55:00 on Warpstar!",
    },
    "Air Ride: MAGMA FLOWS": {
        "Air Ride: MAGMA FLOWS Race over 4,800 feet in 2 minutes!",
        "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:04:00!",
        "Air Ride: Free Run: MAGMA FLOWS Finish 1 lap in under 01:01:00!",
        "Air Ride: MAGMA FLOWS: Use all of the Boost Panels and finish in 1st place!",
        "Air Ride: MAGMA FLOWS Finish 2 laps in under 02:20:00!",
        "Air Ride: Free Run: MAGMA FLOWS Do 1 lap under 01:02:00 on Turbo Star!",
        "Air Ride: MAGMA FLOWS: Use all the volcano rails and finish in 1st place!",
        "Air Ride: MAGMA FLOWS Finish 2 laps in under 02:01:00!",
        "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:20:00!",
        "Air Ride: Free Run: MAGMA FLOWS Finish 1 lap in under 01:10:00!",
        "Air Ride: MAGMA FLOWS: Bump into a flaming dragon!",
        "Air Ride: Time Attack: MAGMA FLOWS Finish in under 03:15:00 on Shadow Star!",
    },
    "Air Ride: FANTASY MEADOWS": {
        "Air Ride: FANTASY MEADOWS Race over 4,500 feet in 2 minutes!",
        "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:00:00!",
        "Air Ride: Free Run: FANTASY MEADOWS Finish 1 lap in under 00:21:00!",
        "Air Ride: FANTASY MEADOWS: Race 1 lap without dropping below 20 mph!",
        "Air Ride: FANTASY MEADOWS Finish 3 laps in under 01:20:00!",
        "Air Ride: Free Run: FANTASY MEADOWS Do 1 lap under 00:23:00 on Wagon Star!",
        "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:05:00 on Slick Star!",
        "Air Ride: FANTASY MEADOWS Finish 3 laps in under 01:03:00!",
        "Air Ride: Time Attack: FANTASY MEADOWS Finish in under 01:12:00!",
        "Air Ride: Free Run: FANTASY MEADOWS Finish 1 lap in under 00:24:00!",
        "Air Ride: FANTASY MEADOWS: Swallow over 20 enemies and take 1st place!",
    },
    "Air Ride: SKY SANDS": {
        "Air Ride: Time Attack: SKY SANDS Finish in under 02:40:00!",
        "Air Ride: SKY SANDS: Enter the quicksand 3 times and finish in 1st place!",
        "Air Ride: Time Attack: SKY SANDS Finish in under 02:40:00 on Wagon Star!",
        "Air Ride: SKY SANDS Finish 2 laps in under 01:45:00!",
        "Air Ride: Free Run: SKY SANDS Finish 1 lap in under 01:05:00!",
        "Air Ride: SKY SANDS Race over 4,000 feet in 2 minutes!",
        "Air Ride: Free Run: SKY SANDS Finish 1 lap in under 00:53:00!",
        "Air Ride: SKY SANDS: Open the trapdoor exactly 3 times and finish in 1st place!",
        "Air Ride: SKY SANDS Finish 2 laps in under 02:05:00!",
        "Air Ride: Time Attack: SKY SANDS Finish in under 03:10:00!",
        "Air Ride: Free Run: SKY SANDS Do 1 lap under 01:05:00 on Bulk Star!",
        "Air Ride: SKY SANDS: Break all of the coral and finish in 1st place!",
    },
    "Air Ride: MACHINE PASSAGE": {
        "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 02:48:00!",
        "Air Ride: MACHINE PASSAGE Race over 4,500 feet in 2 minutes!",
        "Air Ride: MACHINE PASSAGE Finish 2 laps in under 01:48:00!",
        "Air Ride: Free Run: MACHINE PASSAGE Finish 1 lap in under 01:05:00!",
        "Air Ride: MACHINE PASSAGE: Finish in 1st place without touching the walls even once!",
        "Air Ride: MACHINE PASSAGE Finish 2 laps in under 02:10:00!",
        "Air Ride: Free Run: MACHINE PASSAGE Finish 1 lap in under 00:56:00!",
        "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 02:50:00 on Rex Wheelie!",
        "Air Ride: Time Attack: MACHINE PASSAGE Finish in under 03:10:00!",
        "Air Ride: Free Run: MACHINE PASSAGE Do 1 lap under 00:57:00 on Swerve Star!",
        "Air Ride: MACHINE PASSAGE: Shoot 3 characters out of the cannon at one time!",
    },
    "Air Ride: CELESTIAL VALLEY": {
        "Air Ride: CELESTIAL VALLEY Finish 2 laps in under 01:56:00!",
        "Air Ride: Free Run: CELESTIAL VALLEY Do 1 lap under 01:02:00 on Slick Star!",
        "Air Ride: CELESTIAL VALLEY: Use the Copy Chance Wheel on top of the tree!",
        "Air Ride: CELESTIAL VALLEY Race over 6,000 feet in 2 minutes!",
        "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 03:20:00!",
        "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 02:58:00 on Jet Star!",
        "Air Ride: CELESTIAL VALLEY Finish 2 laps in under 02:20:00!",
        "Air Ride: Time Attack: CELESTIAL VALLEY Finish in under 02:56:00!",
        "Air Ride: Free Run: CELESTIAL VALLEY Finish 1 lap in under 01:10:00!",
        "Air Ride: CELESTIAL VALLEY: Over one race, ride on both the left and right bridge railings!",
        "Air Ride: Free Run: CELESTIAL VALLEY Finish 1 lap in under 00:57:00!",
    },
    "Air Ride: FROZEN HILLSIDE": {
        "Air Ride: Free Run: FROZEN HILLSIDE Finish 1 lap in under 01:10:00!",
        "Air Ride: FROZEN HILLSIDE Race 2 laps in under 02:20:00!",
        "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 03:14:00!",
        "Air Ride: Free Run: FROZEN HILLSIDE Finish 1 lap in under 00:58:00!",
        "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 03:10:00 on Turbo Star!",
        "Air Ride: FROZEN HILLSIDE Finish 2 laps in under 01:56:00!",
        "Air Ride: Time Attack: FROZEN HILLSIDE Finish in under 02:50:00!",
        "Air Ride: Free Run: FROZEN HILLSIDE Do 1 lap under 01:10:00 on Formula Star!",
        "Air Ride: FROZEN HILLSIDE: Split at least 20 ice platforms and finish in 1st place!",
        "Air Ride: FROZEN HILLSIDE Race over 5,300 feet in 2 minutes!",
    },
    "Air Ride: BEANSTALK PARK": {
        "Air Ride: BEANSTALK PARK Finish 2 laps in under 01:56:00!",
        "Air Ride: Free Run: BEANSTALK PARK Do 1 lap under 00:58:00 on Winged Star!",
        "Air Ride: BEANSTALK PARK Finish 2 laps in under 02:18:00!",
        "Air Ride: Time Attack: BEANSTALK PARK Finish in under 03:10:00!",
        "Air Ride: BEANSTALK PARK: Race over 3 laps without riding the Ferris wheel!",
        "Air Ride: Time Attack: BEANSTALK PARK Finish in under 03:00:00 on Rocket Star!",
        "Air Ride: BEANSTALK PARK Race over 5,500 feet in 2 minutes!",
        "Air Ride: Time Attack: BEANSTALK PARK Finish in under 02:55:00!",
        "Air Ride: Free Run: BEANSTALK PARK Finish 1 lap in under 01:07:00!",
        "Air Ride: BEANSTALK PARK: Swallow over 20 enemies and take 1st place!",
        "Air Ride: Free Run: BEANSTALK PARK Finish 1 lap in under 00:58:00!",
    },
    "Air Ride: CHECKER KNIGHTS": {
        "Air Ride: Free Run: CHECKER KNIGHTS Finish 1 lap in under 01:35:00!",
        "Air Ride: CHECKER KNIGHTS: Break at least 2 walls and finish in 1st place!",
        "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 04:30:00!",
        "Air Ride: Free Run: CHECKER KNIGHTS Finish 1 lap in under 01:20:00!",
        "Air Ride: CHECKER KNIGHTS: Swallow over 20 enemies and finish in 1st place!",
        "Air Ride: CHECKER KNIGHTS Finish 2 laps in under 02:40:00!",
        "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 04:00:00!",
        "Air Ride: Free Run: CHECKER KNIGHTS Do 1 lap under 01:25:00 on Rocket Star!",
        "Air Ride: CHECKER KNIGHTS Race over 5,500 feet in 2 minutes!",
        "Air Ride: CHECKER KNIGHTS Finish 2 laps in under 03:05:00!",
        "Air Ride: CHECKER KNIGHTS: Use spin panels 7 times or more and take 1st place!",
        "Air Ride: Time Attack: CHECKER KNIGHTS Finish in under 03:55:00 on Warpstar!",
    },
    "Air Ride: High Effort": {
        "Air Ride: Defeat 100 or more enemies with exhaled stars!",
        "Air Ride: Glide for more than 1 hour!",
        "Air Ride: Swallow 200 or more enemies!",
        "Air Ride: Glide for more than 30 minutes!",
        "Air Ride: Defeat over 1,000 of your enemies!",
        "Air Ride: Race over 300 laps!",
        "Air Ride: Fill in over 100 Checklist blocks!",
        "Air Ride: Defeat over 300 of your enemies!",
        "Air Ride: Race over 100 laps!",
    },
}
